export function counterValue(data, name) {
  return data.metrics[name]?.values?.count || 0;
}

export function metricValue(data, name, key) {
  return data.metrics[name]?.values?.[key];
}

export function rateValue(data, name) {
  return data.metrics[name]?.values?.rate;
}

export function formatNumber(value, digits = 2) {
  if (value === undefined || value === null || Number.isNaN(value)) return "-";
  return Number(value).toFixed(digits);
}

export function formatPercent(value) {
  if (value === undefined || value === null || Number.isNaN(value)) return "-";
  return `${formatNumber(value * 100, 2)}%`;
}

// Format bytes (k6 reports data sent/received in bytes).
export function formatBytes(bytes) {
  if (bytes === undefined || bytes === null || Number.isNaN(bytes)) return "-";
  const units = ["B", "KB", "MB", "GB"];
  let value = Number(bytes);
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex += 1;
  }
  return `${formatNumber(value, value >= 100 || unitIndex === 0 ? 0 : 2)} ${units[unitIndex]}`;
}

// Bilingual "not available" fallback for metric values that k6 did not collect.
const NA = { en: "Not available", tr: "Mevcut değil" };

function safeMetricMs(data, name, key) {
  const value = metricValue(data, name, key);
  return value === undefined || value === null ? NA : `${formatNumber(value)} ms`;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function tr(key, lang) {
  const dict = {
    en: {
      verdict: "Verdict",
      purpose: "Purpose",
      read: "How to read this report",
      kpi: "Dashboard",
      checks: "Checks",
      thresholds: "Thresholds",
      counters: "Status Counters",
      interpretation: "Interpretation",
      next: "Next Action",
      metric: "Metric",
      value: "Value",
      explanation: "Explanation",
      passed: "Passed",
      failed: "Failed",
      meaning: "Meaning",
      rule: "Rule",
      status: "Status",
      navOverview: "Overview",
      navLatency: "Latency",
      navThroughput: "Throughput",
      navChecks: "Checks",
      navCounters: "Counters",
      navInterpretation: "Interpretation",
      language: "Language",
      configTitle: "Test Configuration",
      vus: "Virtual Users",
      duration: "Duration",
      iterations: "Iterations",
      timestamp: "Test Ran At",
      summary: "Executive Summary",
      footerGenerated: "Generated by k6 + custom html-report.js",
      baseUrls: "Base URL",
      environment: "Environment",
      testType: "Test Type",
      scenarioName: "Scenario",
      buildId: "Build ID",
      commitSha: "Commit SHA",
      jsonOutput: "Raw JSON Output",
      jsonOutputExp: "A machine-readable k6 summary is also written next to this HTML report for CI/CD and dashboard use.",
      percentiles: "Response Time Percentiles",
      percentile: "Percentile",
      avg: "Average",
      min: "Minimum",
      med: "Median",
      max: "Maximum",
      p90: "p90",
      p95: "p95",
      p99: "p99",
      percentileExp: "Higher percentiles (p90/p95/p99) reveal the slowest requests. These are the values that most affect user-perceived performance.",
      throughput: "Throughput",
      avgRps: "Average RPS",
      totalRequests: "Total Requests",
      dataSent: "Data Sent",
      dataReceived: "Data Received",
      dataExp: "Bytes transferred over the whole run, as reported by k6.",
      peakRpsNa: "Peak RPS requires time-series output such as JSON/InfluxDB/Prometheus remote write.",
      latencyBreakdown: "Latency Breakdown",
      latencyExp: "How each request's time was spent. 'waiting' is time waiting for the server response and usually dominates transfer latency.",
      metricPhase: "Phase",
      notAvailable: "Not available",
      prodGuard: "Production Guard",
      prodGuardActive: "Active — load/race/spike tests refuse to run against production-like targets unless ALLOW_PROD_LOAD_TEST=true.",
      prodGuardSmoke: "Skipped — smoke checks may run against any environment.",
    },
    tr: {
      verdict: "Karar",
      purpose: "Amaç",
      read: "Bu rapor nasıl okunur",
      kpi: "Dashboard",
      checks: "Kontroller",
      thresholds: "Eşikler",
      counters: "Durum Sayaçları",
      interpretation: "Yorum",
      next: "Sonraki Aksiyon",
      metric: "Metrik",
      value: "Değer",
      explanation: "Açıklama",
      passed: "Başarılı",
      failed: "Başarısız",
      meaning: "Anlamı",
      rule: "Kural",
      status: "Durum",
      navOverview: "Özet",
      navLatency: "Gecikme",
      navThroughput: "Trafik Hacmi",
      navChecks: "Kontroller",
      navCounters: "Sayaçlar",
      navInterpretation: "Yorum",
      language: "Dil",
      configTitle: "Test Yapılandırması",
      vus: "Sanal Kullanıcı",
      duration: "Süre",
      iterations: "İterasyon",
      timestamp: "Test Zamanı",
      summary: "Özet Durum",
      footerGenerated: "k6 + custom html-report.js ile üretildi",
      baseUrls: "Base URL",
      environment: "Ortam",
      testType: "Test Tipi",
      scenarioName: "Senaryo",
      buildId: "Build ID",
      commitSha: "Commit SHA",
      jsonOutput: "Ham JSON Çıktısı",
      jsonOutputExp: "Bu HTML raporun yanında CI/CD ve dashboard kullanımı için makine tarafından okunabilir bir k6 özeti de yazılır.",
      percentiles: "Yanıt Süresi Yüzdelikleri",
      percentile: "Yüzdelik",
      avg: "Ortalama",
      min: "Minimum",
      med: "Medyan",
      max: "Maksimum",
      p90: "p90",
      p95: "p95",
      p99: "p99",
      percentileExp: "Yüksek yüzdelikler (p90/p95/p99) en yavaş istekleri gösterir. Kullanıcının hissettiği performansı en çok bu değerler etkiler.",
      throughput: "Trafik Hacmi",
      avgRps: "Ortalama RPS",
      totalRequests: "Toplam İstek",
      dataSent: "Gönderilen Veri",
      dataReceived: "Alınan Veri",
      dataExp: "Tüm koşu boyunca aktarılan bayt miktarı (k6 tarafından raporlanır).",
      peakRpsNa: "Tepe RPS için JSON/InfluxDB/Prometheus remote write gibi zaman serisi çıktısı gerekir.",
      latencyBreakdown: "Gecikme Dağılımı",
      latencyExp: "Her isteğin süresinin nerede geçtiği. 'waiting' sunucu cevabı beklenen süredir ve genelde transfer gecikmesinin büyük kısmıdır.",
      metricPhase: "Faz",
      notAvailable: "Mevcut değil",
      prodGuard: "Üretim Koruması",
      prodGuardActive: "Aktif — load/race/spike testleri, ALLOW_PROD_LOAD_TEST=true olmadan üretim benzeri hedeflerde çalışmayı reddeder.",
      prodGuardSmoke: "Atlandı — smoke kontrolü her ortamda çalışabilir.",
    },
  };

  return dict[lang]?.[key] || dict.en[key] || key;
}

function localize(value, lang) {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value[lang] || value.en || value.tr || "";
  }
  return value;
}

function localizeList(list, lang) {
  return (list || []).map((item) => localize(item, lang));
}

function buildConfigBanner(data, options, lang) {
  const state = data.state || {};
  const meta = options.metadata || {};
  const vus = state.testRunDurationMs ? (data.metrics?.vus?.values?.max || "-") : "-";
  const duration = state.testRunDurationMs
    ? `${formatNumber(state.testRunDurationMs / 1000, 1)}s`
    : "-";
  const iterations = counterValue(data, "iterations");
  const timestamp = state.isStdOutTTY !== undefined ? new Date().toISOString().replace("T", " ").slice(0, 19) : "-";
  const val = (v) => (v === undefined || v === null || v === "" ? "-" : String(v));

  // Each item is only rendered when it has a meaningful value, so smoke tests
  // (which have no scenario name / build id) do not show empty placeholders.
  const item = (labelKey, value, escape = true) => {
    const display = value === "-" ? "-" : escape ? escapeHtml(value) : value;
    return `<div class="config-item"><span class="config-label">${tr(labelKey, lang)}</span><span class="config-val">${display}</span></div>`;
  };

  const items = [
    item("vus", vus),
    item("duration", duration),
    item("iterations", iterations),
    item("timestamp", timestamp),
  ];

  if (val(meta.baseUrl) !== "-") items.push(item("baseUrls", val(meta.baseUrl)));
  if (val(meta.environment) !== "-") items.push(item("environment", val(meta.environment)));
  if (val(meta.testType) !== "-") items.push(item("testType", val(meta.testType)));
  if (val(meta.scenarioName) !== "-") items.push(item("scenarioName", val(meta.scenarioName)));
  if (val(meta.buildId) !== "-") items.push(item("buildId", val(meta.buildId)));
  if (val(meta.commitSha) !== "-") items.push(item("commitSha", val(meta.commitSha)));

  return `<div class="config-banner">
    ${items.join("\n    ")}
  </div>`;
}

function buildExecutiveSummary(data, options, lang) {
  const verdict = options.verdict(data);
  const totalReqs = counterValue(data, "http_reqs");
  const failRate = rateValue(data, "http_req_failed");
  const failPct = failRate !== undefined ? formatPercent(failRate) : "-";
  const p95 = formatNumber(metricValue(data, "http_req_duration", "p(95)"));
  const statusLabel = verdict.ok ? "PASS" : "FAIL";

  const highFailButPass = verdict.ok && failRate > 0.5;

  const text = {
    en: highFailButPass
      ? `${totalReqs.toLocaleString()} requests. k6 HTTP fail rate: ${failPct} (expected — k6 counts 409 as failed). p95: ${p95} ms. Verdict: ${statusLabel}.`
      : `${totalReqs.toLocaleString()} requests. HTTP fail rate: ${failPct}. p95: ${p95} ms. Verdict: ${statusLabel}.`,
    tr: highFailButPass
      ? `${totalReqs.toLocaleString()} istek. k6 HTTP hata oranı: ${failPct} (beklenen — k6, 409'u failed sayar). p95: ${p95} ms. Karar: ${statusLabel}.`
      : `${totalReqs.toLocaleString()} istek. HTTP hata oranı: ${failPct}. p95: ${p95} ms. Karar: ${statusLabel}.`,
  };

  return `<div class="exec-summary ${verdict.ok ? "pass" : "fail"}">
    <span class="exec-icon">${verdict.ok ? "&#10003;" : "&#10007;"}</span>
    <span>${escapeHtml(text[lang] || text.en)}</span>
  </div>`;
}

function buildCheckRows(data, explanations, lang) {
  const checks = data.root_group?.checks || [];
  if (checks.length === 0) return `<tr><td colspan="5" class="muted">No checks.</td></tr>`;

  return checks.map((check) => {
    const passes = check.passes || 0;
    const fails = check.fails || 0;
    const total = passes + fails;
    const passRateNum = total === 0 ? 0 : (passes / total) * 100;
    const passRate = total === 0 ? "-" : `${formatNumber(passRateNum, 1)}%`;
    const ok = fails === 0;
    const barColor = ok ? "var(--green)" : "var(--red)";

    return `<tr>
      <td><span class="dot ${ok ? "good" : "bad-dot"}"></span>${escapeHtml(check.name)}</td>
      <td>
        <div class="progress-bar-wrap">
          <div class="progress-bar" style="width:${passRateNum}%;background:${barColor}"></div>
        </div>
        <strong>${passRate}</strong>
      </td>
      <td>${passes}</td>
      <td>${fails}</td>
      <td>${escapeHtml(localize(explanations[check.name], lang) || "-")}</td>
    </tr>`;
  }).join("\n");
}

function buildThresholdRows(data, explanations, lang) {
  const rows = [];

  for (const [metricName, metric] of Object.entries(data.metrics)) {
    if (!metric.thresholds) continue;

    for (const [expression, threshold] of Object.entries(metric.thresholds)) {
      rows.push(`<tr>
        <td>${escapeHtml(metricName)}</td>
        <td><code>${escapeHtml(expression)}</code></td>
        <td><span class="pill ${threshold.ok ? "pass" : "fail"}">${threshold.ok ? "PASS" : "FAIL"}</span></td>
        <td>${escapeHtml(localize(explanations[metricName], lang) || "-")}</td>
      </tr>`);
    }
  }

  return rows.length ? rows.join("\n") : `<tr><td colspan="4" class="muted">No thresholds.</td></tr>`;
}

function counterTone(name, value) {
  if (value === 0) return "zero";
  if (name === "status_500") return "danger";
  if (name === "status_other") return "warning";
  if (name === "status_201" || name === "status_200") return "success";
  if (name === "status_409") return "conflict";
  return "neutral";
}

function buildCounterCards(data, counters, lang) {
  if (!counters || counters.length === 0) {
    return `<div class="empty">No custom counters.</div>`;
  }

  return counters.map((counter) => {
    const val = counterValue(data, counter.name);
    const tone = counterTone(counter.name, val);
    return `<article class="counter-card ${tone}">
    <div class="counter-name">${escapeHtml(counter.name)}</div>
    <div class="counter-value">${val}</div>
    <p>${escapeHtml(localize(counter.explanation, lang))}</p>
  </article>`;
  }).join("\n");
}

function metricCard(label, value, explanation, tone = "neutral") {
  return `<article class="metric-card ${tone}">
    <div class="metric-label">${escapeHtml(label)}</div>
    <div class="metric-value">${escapeHtml(value)}</div>
    <p>${escapeHtml(explanation)}</p>
  </article>`;
}

function baseMetricCards(data, lang) {
  const text = {
    en: {
      req: "Total Requests",
      reqExp: "All HTTP requests sent during this run.",
      fail: "HTTP Fail Rate",
      failExp: "k6 marks 4xx/5xx as failed. Expected 409 conflicts may inflate this.",
      p95: "p95 Latency",
      p95Exp: "95% of requests completed below this value.",
      avg: "Avg Latency",
      avgExp: "Mean response time across requests.",
      max: "Max Latency",
      maxExp: "Slowest observed request.",
      iterations: "Iterations",
      iterationsExp: "Completed scenario iterations.",
    },
    tr: {
      req: "Toplam İstek",
      reqExp: "Bu koşuda gönderilen tüm HTTP istekleri.",
      fail: "HTTP Hata Oranı",
      failExp: "k6 4xx/5xx cevapları failed sayar. Beklenen 409 conflict bu oranı yükseltebilir.",
      p95: "p95 Gecikme",
      p95Exp: "İsteklerin %95'i bu sürenin altında tamamlandı.",
      avg: "Ort. Gecikme",
      avgExp: "Tüm isteklerin ortalama cevap süresi.",
      max: "Maks Gecikme",
      maxExp: "Gözlenen en yavaş istek.",
      iterations: "İterasyon",
      iterationsExp: "Tamamlanan senaryo iterasyonu.",
    },
  }[lang];

  return [
    metricCard(text.req, String(counterValue(data, "http_reqs")), text.reqExp),
    metricCard(text.fail, formatPercent(rateValue(data, "http_req_failed")), text.failExp, rateValue(data, "http_req_failed") > 0 ? "warn" : "good"),
    metricCard(text.p95, `${formatNumber(metricValue(data, "http_req_duration", "p(95)"))} ms`, text.p95Exp),
    metricCard(text.avg, `${formatNumber(metricValue(data, "http_req_duration", "avg"))} ms`, text.avgExp),
    metricCard(text.max, `${formatNumber(metricValue(data, "http_req_duration", "max"))} ms`, text.maxExp),
    metricCard(text.iterations, String(counterValue(data, "iterations")), text.iterationsExp),
  ];
}

function buildFooter(lang) {
  const now = new Date().toISOString().replace("T", " ").slice(0, 19);
  return `<footer class="report-footer">
    <span>${tr("footerGenerated", lang)}</span>
    <span>${now} UTC</span>
  </footer>`;
}

// Response time percentiles table from http_req_duration.
function buildPercentilesSection(data, lang) {
  const rows = [
    { key: "avg", label: tr("avg", lang) },
    { key: "min", label: tr("min", lang) },
    { key: "med", label: tr("med", lang) },
    { key: "p(90)", label: tr("p90", lang) },
    { key: "p(95)", label: tr("p95", lang) },
    { key: "p(99)", label: tr("p99", lang) },
    { key: "max", label: tr("max", lang) },
  ];

  const body = rows
    .map((row) => {
      const value = safeMetricMs(data, "http_req_duration", row.key);
      return `<tr><td><strong>${escapeHtml(row.label)}</strong></td><td>${escapeHtml(value)}</td></tr>`;
    })
    .join("\n");

  return `<section class="panel" id="${lang}-latency">
    <h2>${tr("percentiles", lang)}</h2>
    <p class="muted">${tr("percentileExp", lang)}</p>
    <div class="table-wrap"><table><thead><tr><th>${tr("percentile", lang)}</th><th>${tr("value", lang)}</th></tr></thead><tbody>${body}</tbody></table></div>
  </section>`;
}

// Latency breakdown: blocked / connecting / tls / sending / waiting / receiving.
function buildLatencyBreakdownSection(data, lang) {
  const metrics = [
    { name: "http_req_blocked", label: { en: "blocked", tr: "blocked" } },
    { name: "http_req_connecting", label: { en: "connecting", tr: "connecting" } },
    { name: "http_req_tls_handshaking", label: { en: "tls_handshaking", tr: "tls_handshaking" } },
    { name: "http_req_sending", label: { en: "sending", tr: "sending" } },
    { name: "http_req_waiting", label: { en: "waiting", tr: "waiting" } },
    { name: "http_req_receiving", label: { en: "receiving", tr: "receiving" } },
  ];

  const statKeys = ["avg", "med", "p(90)", "p(95)", "p(99)", "max"];

  const header = `<tr><th>${tr("metric", lang)}</th>${statKeys.map((k) => `<th>${escapeHtml(k)}</th>`).join("")}</tr>`;

  const body = metrics
    .map((m) => {
      const cells = statKeys
        .map((k) => `<td>${escapeHtml(safeMetricMs(data, m.name, k))}</td>`)
        .join("");
      return `<tr><td><code>${escapeHtml(localize(m.label, lang))}</code></td>${cells}</tr>`;
    })
    .join("\n");

  return `<section class="panel">
    <h2>${tr("latencyBreakdown", lang)}</h2>
    <p class="muted">${tr("latencyExp", lang)}</p>
    <div class="table-wrap"><table><thead>${header}</thead><tbody>${body}</tbody></table></div>
  </section>`;
}

// Throughput: average RPS, total requests, data sent / received.
// Peak RPS is intentionally NOT faked — see peakRpsNa wording.
function buildThroughputSection(data, lang) {
  const totalReqs = counterValue(data, "http_reqs");
  const rps = rateValue(data, "http_reqs");
  const dataSent = metricValue(data, "data_sent", "count");
  const dataReceived = metricValue(data, "data_received", "count");

  const rows = [
    metricCard(tr("totalRequests", lang), String(totalReqs), localize({ en: "All HTTP requests sent during this run.", tr: "Bu koşuda gönderilen tüm HTTP istekleri." }, lang)),
    metricCard(tr("avgRps", lang), rps !== undefined ? formatNumber(rps, 2) : "-", localize({ en: "Average requests per second over the whole run.", tr: "Tüm koşu boyunca saniyedeki ortalama istek." }, lang)),
    metricCard(tr("dataSent", lang), formatBytes(dataSent), localize({ en: "Bytes sent to the server.", tr: "Sunucuya gönderilen bayt." }, lang)),
    metricCard(tr("dataReceived", lang), formatBytes(dataReceived), localize({ en: "Bytes received from the server.", tr: "Sunucudan alınan bayt." }, lang)),
  ];

  return `<section class="panel" id="${lang}-throughput">
    <h2>${tr("throughput", lang)}</h2>
    <p class="muted">${tr("dataExp", lang)}</p>
    <div class="metric-grid">${rows.join("\n")}</div>
    <div class="callout-box"><p>${tr("peakRpsNa", lang)}</p></div>
  </section>`;
}

// Raw JSON output reference (path only — the file is written by handleSummary).
function buildJsonOutputSection(options, lang) {
  const meta = options.metadata || {};
  const path = meta.jsonReportPath || "-";
  return `<section class="panel">
    <h2>${tr("jsonOutput", lang)}</h2>
    <p>${tr("jsonOutputExp", lang)}</p>
    <p><code>${escapeHtml(path)}</code></p>
  </section>`;
}

// Production guard status line.
function buildProdGuardSection(options, lang) {
  const meta = options.metadata || {};
  const smoke = (meta.testType || "").toLowerCase() === "smoke";
  const text = smoke ? tr("prodGuardSmoke", lang) : tr("prodGuardActive", lang);
  return `<section class="panel">
    <h2>${tr("prodGuard", lang)}</h2>
    <p>${escapeHtml(text)}</p>
  </section>`;
}

function renderLanguage(data, options, lang) {
  const verdict = options.verdict(data);
  const title = localize(options.title, lang);
  const extraRows = options.extraMetricRows?.(data) || [];
  const customCounters = options.customCounters || [];

  return `<div class="lang-panel" data-lang="${lang}">
    <aside class="sidebar">
      <div class="brand">k6 Report</div>
      <nav>
        <a href="#${lang}-overview">${tr("navOverview", lang)}</a>
        <a href="#${lang}-latency">${tr("navLatency", lang)}</a>
        <a href="#${lang}-throughput">${tr("navThroughput", lang)}</a>
        <a href="#${lang}-checks">${tr("navChecks", lang)}</a>
        <a href="#${lang}-counters">${tr("navCounters", lang)}</a>
        <a href="#${lang}-interpretation">${tr("navInterpretation", lang)}</a>
      </nav>
    </aside>

    <main class="content">
      ${buildConfigBanner(data, options, lang)}

      <header class="hero" id="${lang}-overview">
        <div class="hero-text">
          <div class="eyebrow">${tr("language", lang)}: ${lang.toUpperCase()}</div>
          <h1>${escapeHtml(title)}</h1>
          <p class="purpose">${escapeHtml(localize(options.purpose, lang))}</p>
        </div>
        <div class="verdict-card ${verdict.ok ? "pass" : "fail"}">
          <span class="verdict-label">${tr("verdict", lang)}</span>
          <strong class="verdict-result">${verdict.ok ? "PASS" : "FAIL"}</strong>
          <p>${escapeHtml(localize(verdict.message, lang))}</p>
        </div>
      </header>

      ${buildExecutiveSummary(data, options, lang)}

      <section class="metric-grid" aria-label="${tr("kpi", lang)}">
        ${baseMetricCards(data, lang).join("\n")}
        ${extraRows.map((item) => metricCard(localize(item.label, lang), String(item.value), localize(item.explanation, lang))).join("\n")}
      </section>

      <section class="callout-box">
        <h2>${tr("read", lang)}</h2>
        <ul>${localizeList(options.howToRead, lang).map((item) => `<li>${escapeHtml(item)}</li>`).join("\n")}</ul>
      </section>

      ${buildPercentilesSection(data, lang)}

      ${buildThroughputSection(data, lang)}

      <section class="two-col" id="${lang}-checks">
        <article class="panel">
          <h2>${tr("checks", lang)}</h2>
          <div class="table-wrap"><table><thead><tr><th>Check</th><th>Pass %</th><th>${tr("passed", lang)}</th><th>${tr("failed", lang)}</th><th>${tr("meaning", lang)}</th></tr></thead><tbody>${buildCheckRows(data, options.checkExplanations || {}, lang)}</tbody></table></div>
        </article>
        <article class="panel">
          <h2>${tr("thresholds", lang)}</h2>
          <div class="table-wrap"><table><thead><tr><th>${tr("metric", lang)}</th><th>${tr("rule", lang)}</th><th>${tr("status", lang)}</th><th>${tr("meaning", lang)}</th></tr></thead><tbody>${buildThresholdRows(data, options.thresholdExplanations || {}, lang)}</tbody></table></div>
        </article>
      </section>

      <section class="panel" id="${lang}-counters">
        <h2>${tr("counters", lang)}</h2>
        <div class="counter-grid">${buildCounterCards(data, customCounters, lang)}</div>
      </section>

      ${buildLatencyBreakdownSection(data, lang)}

      <section class="panel interpretation-panel" id="${lang}-interpretation">
        <h2>${tr("interpretation", lang)}</h2>
        <ul class="interp-list">${localizeList(options.interpretation(data), lang).map((item) => `<li>${escapeHtml(item)}</li>`).join("\n")}</ul>
        <h2>${tr("next", lang)}</h2>
        <div class="next-action-box">
          <p>${escapeHtml(localize(options.nextAction(data), lang))}</p>
        </div>
      </section>

      ${buildProdGuardSection(options, lang)}

      ${buildJsonOutputSection(options, lang)}

      ${buildFooter(lang)}
    </main>
  </div>`;
}

export function generateHtmlReport(data, options) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(localize(options.title, "en"))}</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f0f4f9;
      --panel: #ffffff;
      --text: #0f172a;
      --muted: #64748b;
      --line: #e2e8f0;
      --blue: #2563eb;
      --blue-light: #dbeafe;
      --green: #16a34a;
      --green-light: #dcfce7;
      --green-dark: #166534;
      --red: #dc2626;
      --red-light: #fee2e2;
      --red-dark: #991b1b;
      --amber: #d97706;
      --amber-light: #fef3c7;
      --amber-dark: #92400e;
      --indigo-light: #e0e7ff;
      --shadow: 0 4px 24px rgba(15,23,42,.06);
      --shadow-lg: 0 12px 40px rgba(15,23,42,.1);
      --radius: 16px;
    }

    * { box-sizing: border-box; margin: 0; }
    html { scroll-behavior: smooth; }
    body {
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
      color: var(--text);
      background: var(--bg);
      line-height: 1.5;
    }

    /* Toolbar */
    .toolbar {
      position: sticky; top: 0; z-index: 20;
      display: flex; justify-content: flex-end; gap: 8px;
      padding: 12px 24px;
      background: rgba(240,244,249,.88);
      backdrop-filter: blur(12px);
      border-bottom: 1px solid var(--line);
    }
    .toolbar button {
      border: 1px solid var(--line); background: white; color: var(--text);
      border-radius: 999px; padding: 8px 18px; cursor: pointer;
      font-weight: 700; font-size: 13px; transition: all .15s;
    }
    .toolbar button.active { background: var(--blue); color: white; border-color: var(--blue); }
    .toolbar button:hover:not(.active) { background: var(--blue-light); }

    /* Layout */
    .lang-panel { display: none; min-height: 100vh; }
    .lang-panel.active { display: grid; grid-template-columns: 220px 1fr; }

    .sidebar {
      position: sticky; top: 49px; height: calc(100vh - 49px);
      padding: 28px 16px; border-right: 1px solid var(--line);
      background: rgba(255,255,255,.8); backdrop-filter: blur(12px);
    }
    .brand { font-weight: 900; font-size: 18px; margin-bottom: 28px; letter-spacing: -.03em; color: var(--blue); }
    nav { display: flex; flex-direction: column; gap: 4px; }
    nav a {
      text-decoration: none; color: var(--muted); padding: 10px 12px;
      border-radius: 10px; font-weight: 600; font-size: 14px; transition: all .12s;
    }
    nav a:hover { background: var(--blue-light); color: var(--blue); }

    .content { width: 100%; padding: 28px 32px; max-width: 1200px; }

    /* Config Banner */
    .config-banner {
      display: flex; gap: 24px; flex-wrap: wrap;
      padding: 14px 20px; margin-bottom: 24px;
      background: var(--indigo-light); border-radius: var(--radius);
      border: 1px solid #c7d2fe;
    }
    .config-item { display: flex; flex-direction: column; gap: 2px; }
    .config-label { font-size: 11px; font-weight: 800; text-transform: uppercase; letter-spacing: .1em; color: #4338ca; }
    .config-val { font-size: 15px; font-weight: 700; color: var(--text); }

    /* Hero */
    .hero {
      display: grid; grid-template-columns: 1fr 320px; gap: 20px;
      align-items: stretch; margin-bottom: 20px;
    }
    .hero-text, .verdict-card, .panel, .metric-card, .counter-card {
      background: var(--panel); border: 1px solid var(--line);
      border-radius: var(--radius); box-shadow: var(--shadow);
    }
    .hero-text { padding: 28px; }
    .eyebrow { color: var(--blue); font-weight: 800; text-transform: uppercase; font-size: 11px; letter-spacing: .12em; }
    h1 { margin: 10px 0 12px; font-size: clamp(24px, 3.5vw, 40px); letter-spacing: -.04em; line-height: 1.1; }
    h2 { margin: 0 0 16px; font-size: 17px; letter-spacing: -.02em; font-weight: 800; }
    .purpose { color: var(--muted); line-height: 1.6; font-size: 14px; }
    p { color: var(--muted); line-height: 1.55; }

    /* Verdict */
    .verdict-card {
      padding: 28px; display: flex; flex-direction: column; justify-content: center;
      border-left: 6px solid var(--green);
    }
    .verdict-card.fail { border-left-color: var(--red); }
    .verdict-label { color: var(--muted); font-weight: 800; text-transform: uppercase; font-size: 11px; letter-spacing: .08em; }
    .verdict-result { font-size: 52px; letter-spacing: -.06em; color: var(--green); margin: 4px 0 8px; }
    .verdict-card.fail .verdict-result { color: var(--red); }

    /* Executive Summary */
    .exec-summary {
      display: flex; align-items: center; gap: 12px;
      padding: 16px 20px; margin-bottom: 24px;
      border-radius: var(--radius); font-weight: 600; font-size: 14px;
      border: 1px solid;
    }
    .exec-summary.pass { background: var(--green-light); border-color: #86efac; color: var(--green-dark); }
    .exec-summary.fail { background: var(--red-light); border-color: #fca5a5; color: var(--red-dark); }
    .exec-icon { font-size: 20px; flex-shrink: 0; }

    /* Metric Grid */
    .metric-grid {
      display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));
      gap: 16px; margin-bottom: 24px;
    }
    .metric-card { padding: 20px; min-height: 140px; }
    .metric-card.good { border-top: 4px solid var(--green); }
    .metric-card.warn { border-top: 4px solid var(--amber); }
    .metric-label, .counter-name {
      color: var(--muted); font-size: 11px; text-transform: uppercase;
      font-weight: 800; letter-spacing: .08em;
    }
    .metric-value { font-size: 28px; font-weight: 900; letter-spacing: -.04em; margin: 8px 0 6px; }
    .metric-card p, .counter-card p { font-size: 13px; }

    /* Callout Box (How to Read) */
    .callout-box {
      padding: 20px 24px; margin-bottom: 24px;
      background: var(--amber-light); border: 1px solid #fde68a;
      border-radius: var(--radius); border-left: 5px solid var(--amber);
    }
    .callout-box h2 { color: var(--amber-dark); margin-bottom: 12px; }
    .callout-box ul { margin: 0; padding-left: 20px; color: var(--amber-dark); font-size: 14px; line-height: 1.7; }

    /* Panels */
    .panel { padding: 24px; margin-bottom: 20px; }
    .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px; }

    /* Counter Grid */
    .counter-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 14px; }
    .counter-card { padding: 18px; min-height: 120px; transition: border-color .2s; }
    .counter-card.zero { opacity: 0.5; border-style: dashed; }
    .counter-card.danger { border-color: var(--red); border-left: 5px solid var(--red); background: var(--red-light); }
    .counter-card.warning { border-color: var(--amber); border-left: 5px solid var(--amber); background: var(--amber-light); }
    .counter-card.success { border-color: var(--green); border-left: 5px solid var(--green); background: var(--green-light); }
    .counter-card.conflict { border-color: var(--blue); border-left: 5px solid var(--blue); background: var(--blue-light); }
    .counter-value { font-size: 26px; font-weight: 900; letter-spacing: -.04em; margin: 6px 0; }

    /* Progress Bar in Checks */
    .progress-bar-wrap {
      width: 60px; height: 6px; background: #e2e8f0; border-radius: 99px;
      display: inline-block; vertical-align: middle; margin-right: 8px; overflow: hidden;
    }
    .progress-bar { height: 100%; border-radius: 99px; transition: width .3s; }

    /* Tables */
    .table-wrap { overflow: auto; max-height: 400px; border: 1px solid var(--line); border-radius: 12px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th, td { padding: 11px 14px; border-bottom: 1px solid var(--line); text-align: left; vertical-align: top; }
    th { position: sticky; top: 0; background: #1e293b; color: white; z-index: 1; font-weight: 700; font-size: 12px; text-transform: uppercase; letter-spacing: .04em; }
    td { background: white; }
    code { background: #f1f5f9; border: 1px solid #e2e8f0; padding: 2px 6px; border-radius: 6px; font-size: 12px; }
    .pill { display: inline-block; border-radius: 999px; padding: 4px 10px; font-weight: 800; font-size: 11px; }
    .pill.pass { background: var(--green-light); color: var(--green-dark); }
    .pill.fail { background: var(--red-light); color: var(--red-dark); }
    .dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 8px; background: var(--green); }
    .bad-dot { background: var(--red); }
    .muted { color: var(--muted); }
    .empty { color: var(--muted); padding: 20px; }

    /* Interpretation */
    .interpretation-panel { background: var(--panel); }
    .interp-list { margin: 0 0 20px; padding-left: 20px; color: var(--text); font-size: 14px; line-height: 1.8; }
    .next-action-box {
      padding: 14px 18px; background: var(--blue-light);
      border: 1px solid #93c5fd; border-radius: 12px;
    }
    .next-action-box p { color: var(--text); font-weight: 600; font-size: 14px; }

    /* Footer */
    .report-footer {
      display: flex; justify-content: space-between;
      padding: 16px 0; margin-top: 12px;
      border-top: 1px solid var(--line); color: var(--muted); font-size: 12px;
    }

    /* Responsive */
    @media (max-width: 1180px) {
      .metric-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
      .counter-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
      .hero { grid-template-columns: 1fr; }
    }
    @media (max-width: 820px) {
      .lang-panel.active { display: block; }
      .sidebar { position: relative; top: 0; height: auto; border-right: 0; border-bottom: 1px solid var(--line); }
      nav { flex-direction: row; flex-wrap: wrap; }
      .content { padding: 16px; }
      .two-col { grid-template-columns: 1fr; }
      .metric-grid { grid-template-columns: 1fr; }
      .counter-grid { grid-template-columns: 1fr; }
      .config-banner { flex-direction: column; gap: 12px; }
    }
    @media (max-width: 520px) {
      .toolbar { justify-content: center; }
    }
  </style>
</head>
<body>
  <div class="toolbar"><button class="active" data-switch="en">English</button><button data-switch="tr">Türkçe</button></div>
  ${renderLanguage(data, options, "en")}
  ${renderLanguage(data, options, "tr")}
  <script>
    const buttons = document.querySelectorAll('[data-switch]');
    const panels = document.querySelectorAll('.lang-panel');
    function setLang(lang) {
      buttons.forEach((button) => button.classList.toggle('active', button.dataset.switch === lang));
      panels.forEach((panel) => panel.classList.toggle('active', panel.dataset.lang === lang));
      document.documentElement.lang = lang;
    }
    buttons.forEach((button) => button.addEventListener('click', () => setLang(button.dataset.switch)));
    setLang('en');
  </script>
</body>
</html>`;
}
